import type { StoryPreset } from "./story-experience";

export const EXPERIENCE_PRESETS: Record<string, StoryPreset> = {
  "romance-classico": {
    eyebrow: "Uma história de amor para guardar para sempre",
    momentsTitle: "Os capítulos do nosso amor",
    galleryTitle: "Tudo o que os olhos não esquecem",
    fallbackScheme: "vinho",
    hero: "cover",
    gallery: "mosaic",
    moments: "timeline",
    motif: "heart",
    titleMode: "names",
    showCounter: true,
  },
  "nossa-linha-do-tempo": {
    eyebrow: "Do primeiro encontro até este presente",
    momentsTitle: "Nossa linha do tempo",
    galleryTitle: "Instantes entre um capítulo e outro",
    fallbackScheme: "vinho",
    hero: "editorial",
    gallery: "filmstrip",
    moments: "milestones",
    motif: "heart",
    titleMode: "names",
    showCounter: true,
  },
  "amor-minimalista": {
    eyebrow: "Menos distração. Tudo o que importa.",
    momentsTitle: "Nós, em poucas palavras",
    galleryTitle: "O essencial ficou",
    fallbackScheme: "grafite",
    hero: "split",
    gallery: "editorial",
    moments: "diary",
    motif: "heart",
    titleMode: "names",
    showCounter: true,
  },
  "amigos-para-sempre": {
    eyebrow: "A amizade que virou casa",
    momentsTitle: "As histórias que só a gente entende",
    galleryTitle: "Nosso rolo de câmera",
    fallbackScheme: "âmbar",
    hero: "cover",
    gallery: "polaroid",
    moments: "cards",
    motif: "star",
    titleMode: "names",
  },
  "mural-de-memorias": {
    eyebrow: "Caos bonito, memórias melhores ainda",
    momentsTitle: "Palavras que resumem a gente",
    galleryTitle: "O mural das melhores histórias",
    fallbackScheme: "coral",
    hero: "poster",
    gallery: "mosaic",
    moments: "tags",
    motif: "sparkles",
    titleMode: "title",
  },
  "momentos-da-amizade": {
    eyebrow: "Uma coleção de dias inesquecíveis",
    momentsTitle: "Se cada lembrança pudesse falar",
    galleryTitle: "Do nosso jeito",
    fallbackScheme: "céu",
    hero: "split",
    gallery: "filmstrip",
    moments: "timeline",
    motif: "star",
    titleMode: "names",
  },
  "nossa-familia": {
    eyebrow: "Onde a vida sempre encontra abrigo",
    momentsTitle: "As raízes da nossa história",
    galleryTitle: "Retratos de quem somos",
    fallbackScheme: "oliva",
    hero: "cover",
    gallery: "mosaic",
    moments: "timeline",
    motif: "leaf",
    titleMode: "title",
    showCounter: true,
  },
  "cantinho-da-familia": {
    eyebrow: "Nosso lugar favorito no mundo",
    momentsTitle: "Pequenas grandes lembranças",
    galleryTitle: "Álbum da sala de casa",
    fallbackScheme: "terracota",
    hero: "album",
    gallery: "polaroid",
    moments: "cards",
    motif: "home",
    titleMode: "title",
  },
  "album-da-familia": {
    eyebrow: "Memórias passadas de mão em mão",
    momentsTitle: "Páginas da nossa família",
    galleryTitle: "Retratos para atravessar o tempo",
    fallbackScheme: "areia",
    hero: "editorial",
    gallery: "editorial",
    moments: "diary",
    motif: "home",
    titleMode: "title",
  },
  "melhor-amigo": {
    eyebrow: "Amor com patas, pelos e muita bagunça",
    momentsTitle: "Uma vida inteira de companhia",
    galleryTitle: "Focinho, poses e aventuras",
    fallbackScheme: "céu",
    hero: "cover",
    gallery: "grid",
    moments: "milestones",
    motif: "paw",
    titleMode: "recipient",
  },
  "aventuras-do-pet": {
    eyebrow: "A melhor companhia para explorar o mundo",
    momentsTitle: "O mapa das nossas aventuras",
    galleryTitle: "Postais de cada passeio",
    fallbackScheme: "menta",
    hero: "split",
    gallery: "filmstrip",
    moments: "timeline",
    motif: "paw",
    titleMode: "recipient",
  },
  "diario-do-pet": {
    eyebrow: "Confissões de uma amizade de quatro patas",
    momentsTitle: "Entradas deste diário",
    galleryTitle: "As páginas mais fofas",
    fallbackScheme: "âmbar",
    hero: "album",
    gallery: "polaroid",
    moments: "diary",
    motif: "paw",
    titleMode: "recipient",
  },
  "feliz-aniversario": {
    eyebrow: "Hoje o mundo celebra você",
    momentsTitle: "Motivos para brindar a sua história",
    galleryTitle: "Só os melhores momentos",
    fallbackScheme: "violeta",
    hero: "poster",
    gallery: "mosaic",
    moments: "cards",
    motif: "cake",
    titleMode: "recipient",
  },
  "nossa-trajetoria": {
    eyebrow: "Cada fase trouxe você até aqui",
    momentsTitle: "Uma vida em capítulos",
    galleryTitle: "Cenas dessa trajetória",
    fallbackScheme: "coral",
    hero: "editorial",
    gallery: "editorial",
    moments: "timeline",
    motif: "sparkles",
    titleMode: "recipient",
  },
  "surpresa-de-aniversario": {
    eyebrow: "Tem alguém muito especial fazendo aniversário",
    momentsTitle: "A surpresa começa pelas lembranças",
    galleryTitle: "Um brinde a todos esses sorrisos",
    fallbackScheme: "rosa",
    hero: "cover",
    gallery: "filmstrip",
    moments: "milestones",
    motif: "cake",
    titleMode: "recipient",
  },
  "bem-vindo-bebe": {
    eyebrow: "Um amor inteiramente novo chegou",
    momentsTitle: "Os primeiros capítulos",
    galleryTitle: "Pequenos instantes, amor infinito",
    fallbackScheme: "rosa",
    hero: "cover",
    gallery: "editorial",
    moments: "cards",
    motif: "baby",
    titleMode: "recipient",
    datePrefix: "Chegou em",
  },
  "album-do-bebe": {
    eyebrow: "Um álbum para crescer junto",
    momentsTitle: "Descobertas e primeiras vezes",
    galleryTitle: "Cada detalhe que queremos lembrar",
    fallbackScheme: "céu",
    hero: "album",
    gallery: "polaroid",
    moments: "milestones",
    motif: "baby",
    titleMode: "recipient",
  },
  "mes-a-mes": {
    eyebrow: "Do primeiro colo a cada nova descoberta",
    momentsTitle: "Crescendo diante dos nossos olhos",
    galleryTitle: "Doze meses de puro encanto",
    fallbackScheme: "violeta",
    hero: "split",
    gallery: "grid",
    moments: "timeline",
    motif: "baby",
    titleMode: "recipient",
  },
  "nosso-sim": {
    eyebrow: "Duas histórias escolhendo o mesmo caminho",
    momentsTitle: "Tudo o que nos trouxe até o sim",
    galleryTitle: "O dia que ficou para sempre",
    fallbackScheme: "marfim",
    hero: "cover",
    gallery: "editorial",
    moments: "timeline",
    motif: "rings",
    titleMode: "names",
    showCounter: true,
  },
  "galeria-de-casamento": {
    eyebrow: "Um ensaio sobre amor, presença e promessa",
    momentsTitle: "A história por trás das imagens",
    galleryTitle: "Nossa galeria",
    fallbackScheme: "rosa",
    hero: "editorial",
    gallery: "editorial",
    moments: "cards",
    motif: "rings",
    titleMode: "names",
  },
  "nossos-votos": {
    eyebrow: "Palavras para escolher você outra vez",
    momentsTitle: "Promessas construídas com o tempo",
    galleryTitle: "Entre o que vivemos e o que virá",
    fallbackScheme: "marfim",
    hero: "album",
    gallery: "polaroid",
    moments: "diary",
    motif: "heart",
    titleMode: "names",
  },
};
